name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Choose initial environment to deploy"
        type: choice
        options:
        - test
        - dev
        - staging
      mandatory:
        description: "Mandatory installer"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir dist
          echo "my-app" > dist/app.txt
          
      - name: Echo inputs
        run: |
          echo "Is mandatory: ${{ inputs.mandatory }}
          echo "Is mandatory: ${{ inputs.target_env }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/

  deploy-initial:
    name: Deploy ${{ inputs.target_env }}
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.target_env == 'dev' || inputs.target_env == 'test' }}
    environment: ${{ inputs.target_env }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist/

      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.target_env }}"
          
  deploy-staging:
    needs: [build, deploy-initial]
    runs-on: ubuntu-latest
    if: |
      always() && 
      !cancelled() && 
      (needs.build.result == 'success' || needs.deploy-initial.result == 'success')
    # if: ${{ inputs.target_env == 'staging'}}
    environment: staging

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist/

      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.target_env }}"

  deploy-preprod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: preprod

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist/

      - name: Deploy
        run: |
          echo "Deploying to pre-prod"

  deploy-prod:
    needs: deploy-preprod
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist/

      - name: Deploy
        run: |
          echo "Deploying to prod"
